package com.example.demo.mybatis.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.mybatis.model.AccountInfo;
import com.example.demo.mybatis.model.AccountInfoExample;

@Mapper
public interface AccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    long countByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    int deleteByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    int insert(AccountInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    int insertSelective(AccountInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    List<AccountInfo> selectByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    AccountInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    int updateByExampleSelective(@Param("row") AccountInfo row, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    int updateByExample(@Param("row") AccountInfo row, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    int updateByPrimaryKeySelective(AccountInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account.account_info
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    int updateByPrimaryKey(AccountInfo row);
}