package com.example.demo.mybatis.model;

import java.util.Date;

public class AccountInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_info.id
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_info.account_name
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_info.company
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_info.age
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_info.sex
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_info.language
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_info.employment_type
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    private String employmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_info.register_date
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    private Date registerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_info.id
     *
     * @return the value of account.account_info.id
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_info.id
     *
     * @param id the value for account.account_info.id
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_info.account_name
     *
     * @return the value of account.account_info.account_name
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_info.account_name
     *
     * @param accountName the value for account.account_info.account_name
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_info.company
     *
     * @return the value of account.account_info.company
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_info.company
     *
     * @param company the value for account.account_info.company
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_info.age
     *
     * @return the value of account.account_info.age
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_info.age
     *
     * @param age the value for account.account_info.age
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_info.sex
     *
     * @return the value of account.account_info.sex
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_info.sex
     *
     * @param sex the value for account.account_info.sex
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_info.language
     *
     * @return the value of account.account_info.language
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_info.language
     *
     * @param language the value for account.account_info.language
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_info.employment_type
     *
     * @return the value of account.account_info.employment_type
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public String getEmploymentType() {
        return employmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_info.employment_type
     *
     * @param employmentType the value for account.account_info.employment_type
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public void setEmploymentType(String employmentType) {
        this.employmentType = employmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_info.register_date
     *
     * @return the value of account.account_info.register_date
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_info.register_date
     *
     * @param registerDate the value for account.account_info.register_date
     *
     * @mbg.generated Thu Mar 06 18:04:24 JST 2025
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
}